### ISSUE TITLE
Quality rules

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#11]
These are a set of scripts which generate warnings or errors to be displayed in the UI. For example, a rule might be triggered if attendance isn't marked for a session more than 7 days ago.

Challenges to solve here:

## User interface (objects)

How to present a UI with relevant information without adding clutter. Are there markers on specific objects in the list? Only in the edit view?

## User interface (global)

If there some dashboard location to see all the warnings and errors in one place?

## Recalculation

Scripts need to run periodically but also be recalculated for each object when they are updated. Or possibly triggered and cascaded to related objects.

## Task tracking

Can we push errors to an external task tracker? Or mark them within onCourse as not relevant.

## Storage

Do we store quality results in the database or only in memory?

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/scripts-quality-rules/184
