### ISSUE TITLE
Clustered onCourse servers

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#12]
All our web applications (search, website, checkout, portal, editor, etc) have run as a clustered set of redundant servers since the beginning.

The onCourse admin application has not, but we are quite close to making this possible and having zero downtime upgrades. Right now, upgrading onCourse requires a 20 second outage of the admin application.

- [X] Support database cluster
- [X] Schema upgrades locked to one instance
- [X] Session management moved to database
- [X] All client-server interactions RESTful
- [X] Support load balancer in front of instances
- [X] Health check URL
- [x] Cron jobs locked to one instance
- [x] Replication thread locked to one instance
- [x] Message sending thread locked to one instance
- [ ] Print job data synced across instances
- [x] invoice/student number generation

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/clustered-oncourse-servers/188
