### ISSUE TITLE
Class resources

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#15]
Add resources to a class timetable. This could be equipment (eg cameras for student use), cars for a driving school, etc.

Resources would show on the timetable and could have availability and collision detection.

**Comment by garry-traynor** [comment]
This could indeed be a very useful feature

**Comment by LindaACWA** [comment]
This would be good for us to - while we don't have a lot of courses that need specific resources it would be useful to be able to note this for the ones that do

**Comment by ari** [comment]
What would be some examples of resources that you might want to track?

**Comment by LindaACWA** [comment]
We sometimes use training resources such as specific sets of cards that
stimulate discussion. Some courses need art supplies - one trainer insists
on having textas and A3 paper. So its all random but its easy to forget
that we need to have those things available.

**Comment by ari** [comment]
Got it. That's not in the scope of what we originally had in mind here since I was imagining persistent resources (eg. driving school cars) rather than disposable resources (like art supplies). But I love the idea of making resources work for both.

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/class-resources/196
