### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#17]
ish and its founder have long been strong advocates for open source and contributed thousands of hours toward a range of open source projects.

We are exploring what parts of onCourse itself could become open source and are working to ensure all parts are unencumbered, ready for that move.

As part of this we are evaluating our pricing model to ensure we can continue to have a sustainable business model and give our customers more freedom and control.

- [x] Convert docs to asciidoc
- [x] Remove proprietary doc digrams
- [x] Release docs under CC license
- [x] Create plugin mechanisms in onCourse
- [x] Remove proprietary integrations (like Xero, TCSI, etc)
- [x] Allow plugins to extend data model
- [x] Remove proprietary website replication plugin
- [ ] Choose open bug tracker
- [ ] Review pricing
- [x] Release onCourse under AGPL3

**Comment by ari** [comment]
A step on this path has now been completed. The onCourse docs repository is available here: https://github.com/ishgroup/onCourseDocs

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/move-to-open-source/190
