### ISSUE TITLE
Continuing Professional Development (CPD)

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#18]
onCourse already supports CPD programmes, but there is more we can do to help people track points.

**Comment by garry-traynor** [comment]
Good feature.

**Comment by ari** [comment]
Are there any particular aspects of this you'd find especially valuable? Today Modules (units) have a CPD point field which could be printed on certificates, but there is no tracking of progress.

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/continuing-professional-development-cpd/193
