### ISSUE TITLE
Documents in data collection

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#21]
There are situations were it would be useful for students to be able to upload documents as part of an enrolment or application process. For example, where they need to provide provide of id like a driver's license or some proof of previous qualifications.

We should be able to add a data collection form element of type document for them to submit.

## Problems to solve

* Since our document store is currently non-deletable, we need a way to permanently delete documents uploaded in error. Students could upload offensive or inappropriate material.
* We need to implement size limits
* We need to bill customers for storage since this has the potential to blow out storage sizes
* We should think about document lifecycle rules (eg to delete documents after a period of time)

Perhaps a separate S3 bucket is needed to separate this type of content.

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/documents-in-data-collection/197
