### ISSUE TITLE
Customise income accounts in checkout

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#23]
Although keeping checkout really simple is important, some users would like to be able to select other income accounts during the checkout process both for the student fee and any funding invoice.
Also they want to be able to add additional lines to the funding invoice, to break up the base funding amount from the loading and track them separately on the general ledger.

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/customise-income-accounts-in-checkout/192
