### ISSUE TITLE
Add Next button in Classes page

### ISSUE THREAD

**Issue by Jsch8925** [ishgroup/onCourse-roadmap#24]
Add 'Next' button to the Classes page. This was a feature of the old onCourse and very regularly used.

**Comment by ari** [comment]
Thanks for this ticket. We've kept this feature, but in a different way since the old approach was stateful (the server needed to keep track of where you were up to in the list and synchronise the list with any changes being made by other users).

In the new UI we implemented the three column view where you can navigate through the list and edit/view records as you go. That was specifically done to replace previous/next.

I know it is different, but using a browser as an application UI requires different solutions.

**Comment by Jsch8925** [comment]
Thanks Ari,

I thought it was worth a try!

With the three column view, perhaps there’s a way in the future to display the Budget tab as open? At the moment, you still need to click into each individual class to view it.

Totally understand if not, but from a user perspective it would make my job much easier.


[cid:image001.jpg@01D66FFB.025779D0]

Kind regards,
Jennifer

Jennifer Schmitzer | Senior Administrative Coordinator (Programs)
The University of Sydney
Centre for Continuing Education
Education Portfolio

Rm 101, Darling Building L03F l The University of Sydney
160 Missenden Road | Newtown | NSW | 2042
+61 2 8627 6712
 jennifer.schmitzer@sydney.edu.au<mailto:jennifer.schmitzer@sydney.edu.au> | cce.sydney.edu.au<http://cce.sydney.edu.au/>
CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.

**Comment by ari** [comment]
Sure, as you browse each record should stay scrolled to the same place and with the same sections open. Class might be different because we lazy load some sections like budget but I can take a look.

**Comment by Jsch8925** [comment]
Thanks Ari, no it doesn’t hold the sections open from the previous record unfortunately. If it did that would be very helpful!

Kind regards,
Jennifer

Jennifer Schmitzer | Senior Administrative Coordinator (Programs)
The University of Sydney
Centre for Continuing Education
Education Portfolio

Rm 101, Darling Building L03F l The University of Sydney
160 Missenden Road | Newtown | NSW | 2042
+61 2 8627 6712
 jennifer.schmitzer@sydney.edu.au<mailto:jennifer.schmitzer@sydney.edu.au> | cce.sydney.edu.au<http://cce.sydney.edu.au/>
CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.
