### ISSUE TITLE
Placeholder enrolments

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#25]
Sometimes a class will be scheduled (often for corporate training) without knowing exactly who will be attending, but knowing the number of students.

The specific students might be assigned on the day, depending on working shifts.

This task might overlap with #5 for creating events with a more theatrical style sales process (where only the number of tickets is known and not the individual students).

**Comment by swinbanks** [comment]
moved to https://oncourse.discourse.group/t/placeholder-enrolments/186
