### ISSUE TITLE
Programme enrolments

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#4]
### Mandatory requirements

1. Display programmes on website mixed with normal courses
2. Enrolment in programme gives permission for enrolment in related courses
3. Optionally charge fees at the programme level which optionally gives zero fee enrolments into related courses
4. Related courses may optionally be enrolled into separately
5. One class could contain students funded under multiple programmes

### Optional goals

1. Track progress of student toward some goal like a qualification
2. Order the related courses (eg. prevent enrolment out of order)
3. Core and elective related courses

### Course relations

Give course relations user definable name with some special types:

* Recommendation (current behaviour)
* Next/Previous (French level 2 follows French level 1)
* Bundle (grouped courses often taken together)

### Course relation enforcement

[ ] Mandatory on enrolment

Examples:
* a parent bundle with mandatory children: you must enrol in all courses in the bundle at the same time
* course with mandatory 'next': you must enrol in the next course at the same time

Note that enforcement has special meaning for course by application. So an application in a parent course of a bundle does not require applications into the child courses, but when the application is converted into an enrolment each child course must then be enrolled into at once.

[ ] Prerequisite

Rather than requiring the related course being required in the same checkout, it could also be previously purchased or enrolled in:

Examples:
* course with mandatory 'previous': you must enrol in the previous course (or have previously enrolled in it)

[ ] Soft prerequisite

When enrolling the related course/product is added the checkout, but the user can remove it.

### Course to product relations

The concept of bundles can apply to products as well. So this is a way to add mandatory material or other fees. It would be interesting to be able to bundle a mandatory audition fee with a course application but then we'd need:

[ ] Mandatory on application

Examples:
* A product audition fee

[ ] Prerequisite

Examples:
* A course which the student must have previously been enrolled in

### Enrolment helper

Auto populate core courses the student has not yet enrolled in, show remaining class count for their voucher in the left panel of QE, auto suggest elective courses to quick add

**Comment by garry-traynor** [comment]
Good feature and sounds like a heck of work.

**Comment by ari** [comment]
> Good feature and sounds like a heck of work.

This is a dramatically simpler approach than our original ideas about five years ago to create courses that could be nested inside other courses. So I'm not worried about complexity to build this.

What relationships/groups would you create? I want to make sure this approach maps well to real life use-cases.

**Comment by Waicurrie** [comment]
We are wanting to create an automated link between on course and mailchimp data so that when someone unsubscribes from mailchimp they are unsubscribed from on course. Not sure if this is possible with the on course/ mailchimp integration platform. Just looking at the easiest ways to manage our audience lists once we start distributing these campaigns.

**Comment by jameshandsaker** [comment]
It would be great to keep micro-credentialing in mind when developing this, as I think that is a way we would likely make use of programme enrolments.

**Comment by ari** [comment]
Would you be able to elaborate a little? Are the micro-credentials more like CPD points or are they part of a package of courses you would do sequentially?

**Comment by jameshandsaker** [comment]
We haven't quite got far enough down our thinking to give a perfect answer unfortunately, but I would imagine the structure would be a series of courses that wouldn't necessarily be required to be completed in order but that all need to be completed in order to gain a credential.

**Comment by ari** [comment]
Here is what we've implemented for this feature. Just defaults, so you can make your own, but hopefully this explains how they will effect the checkout and marketing processes.

```
[EntityRelationType]

id: 0
name: Similar courses
description: Other courses you might be interested in
fromName similar
toName: similar
isShownOnWeb: 1
discount: null
shoppingCart: NO_ACTION
considerHistory: 1


id: 1
name: Level progression
description: Courses at other levels of difficulty
fromName previous
toName: next
isShownOnWeb: 1
discount: null
shoppingCart: SUGGESTION
considerHistory: 1


id: 2
name: Bundles
description: Courses are bundled into a discounted package
fromName bundle
toName: component
isShownOnWeb: 1
discount: null
shoppingCart: ADD_NO_REMOVAL
considerHistory: 0


id: 3
name: Application fee
description: A product fee which must be added to checkout
fromName course application
toName: product fee
isShownOnWeb: 1
discount: null
shoppingCart: ADD_NO_REMOVAL
considerHistory: 0


id: 4
name: Rolling intake
description: Flexible course delivery
fromName: rolling intake course
toName: rolling intake subject
isShownOnWeb: 1
discount: null
shoppingCart: ADD_NO_REMOVAL
considerHistory: 1


id: 5
name: Course materials
description: Suggested course materials
fromName: course
toName: course material
isShownOnWeb: 1
discount: null
shoppingCart: ADD_ALLOW_REMOVAL
considerHistory: 0



EntityRelationCartAction
 - NO_ACTION
 - SUGGESTION
 - ADD_ALLOW_REMOVAL
 - ADD_NO_REMOVAL
```

**Comment by ari** [comment]
The key parts of this feature were rolled out in onCourse 53.
