### ISSUE TITLE
CMS Nested Pages

### ISSUE THREAD

**Issue by griffenedge** [ishgroup/onCourse-roadmap#57]
The ability to nest pages in the CMS would make navigating "Pages" significantly easier. Currently, pages are listed in alphabetical order, which works fine when they are all in the root, but if you make use of directories pages quickly get lost from each other. "Menus" already allows nesting, so it would be great to see this brought over.

**Comment by ari** [comment]
Pages don't really have hierarchy since they can be organised into a menu tree in different ways. In fact we might support in the future more than one menu, so there is more than one way to navigate pages.

I understand why you want this, but I don't think a single tree is any more helpful than an alphabetical list.

**Comment by griffenedge** [comment]
I understand how the pages don't have a hierarchy, however, the issue of managing a large number of pages using only an alphabetical list is still there.
This is relevant to us as we have a large number of pages dedicated to different policies and blog posts. Currently, these pages are spread across the "Pages" list, and being able to group them would make managing all pages easier. The WordPress plugin [Nested Pages](https://nestedpages.com/) is a good example of an easy way to manage pages in a CMS.

**Comment by ari** [comment]
With our new updates to the navigation in #editor and the ability to search, hopefully this is easier. Our pages aren't likely to be grouped in a tree any time soon since we aren't encouraging that sort of hierarchy.
