### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#58]
At the moment each Site has a timezone and availability rules. We also have availability rules (holidays) in global preferences, however they don't have a timezone. This makes them inaccurate and difficult to use for organisations with multiple locations across a country or around the world.

If we introduce regions, each Site must be linked to exactly one region. The timezone attribute will be moved from Site to Region.

Regions can have availability rules and the global rules will be removed.

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/introducing-regions/201
