### ISSUE TITLE
Membership prepaid fee liability

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#59]
onCourse currently posts all income for memberships at the time of invoice.This is fine in many cases (eg. membership of a not-for-profit) but not appropriate for subscriptions that look like gym membership.

In that case we'd like to post to prepaid fee liability and journal out to income on the first of each month, very similar to the way class enrolments work today.

**Comment by swinbanks** [comment]
This could be selectable, so users could choose whether they would like the income to be posted all at once, or split evenly over the duration of the subscription

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/membership-prepaid-fee-liability/203
