### ISSUE TITLE
Search for null joins

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#6]
Allow searching for missing joins in our query language. For example find all outcomes not linked to certificate.

**Comment by ari** [comment]
Jira uses the syntax:

`course.classes is EMPTY`

or we could go with a more generic approach like:

`course.classes.count = 0`

That would be more useful for other counting too...

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/search-for-null-joins/181
