### ISSUE TITLE
Inbound email

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#61]
Sometimes it would be useful to store inbound email into onCourse, such as student responses to questions particularly around the application process. However we would want to be careful about:

1. Attaching that email to the correct entity (not just against the student record, but to a specific application)
2. Avoiding storing lots of attachments which clutter document management (email footers, etc)
3. Handling complex untrusted html and displaying that inside the UI. There are security issues here parsing and displaying CSS even without running javascript.

Some thoughts on solutions:

* Connectors to popular email software (gmail/outlook/etc) to make it easy to store an email
* ability to forward as attachment to a special email address inside onCourse. There would need to be tokens or authentication. Plus some queue to allow emails to be properly attached to the right place (eg. contacts may have duplicate emails)
* special tokens in outbound emails so that replies go to the right place (they might get stripped in a reply, so tricky)

Alternatively we just continue to work on integrations with task tracking systems as we've already done where these interactions might better take place: Trello, Zendesk, Jira, Monday, etc.

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/store-inbound-email/204
